apiVersion: v1 
kind: Service 
metadata:
  name: kafka
  labels:  
    app: kafkaApp   
spec: 
  type: LoadBalancer 
  selector:  
      app: kafkaApp 
  ports:  
  - port: 9092 
    targetPort: 9092
    protocol: TCP
  - port: 2181 
    targetPort: 2181
