apiVersion: v1 
kind: Service 
metadata:
  name: kafka
  labels:  
    app: kafkaApp   
spec: 
  type: LoadBalancer 
  selector:  
      app: kafkaApp 
  ports:
  - name: kafka
    port: 9092 
    targetPort: 9092
    protocol: TCP
  - name: client
    port: 2181 
    targetPort: 2181
